update workflows

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -34,14 +34,13 @@ jobs:
 
       - name: Tag and Push image
         run: |
-          # Тег для GHCR
           IMAGE_NAME=ghcr.io/${GITHUB_ACTOR}/vlm_captioning:latest
-          
-          # Получаем ID образа, который собрал docker compose
           IMAGE_ID=$(docker compose images -q vlm_captioning)
           
-          # Тегируем образ
-          docker tag $IMAGE_ID $IMAGE_NAME
+          if [ -z "$IMAGE_ID" ]; then
+            echo "ERROR: Image ID not found. Build failed?"
+            exit 1
+          fi
           
-          # Пушим образ в GHCR
+          docker tag $IMAGE_ID $IMAGE_NAME
           docker push $IMAGE_NAME
